# Generated by Django 6.0.3 on 2026-03-15 18:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                ("codigo", models.IntegerField(unique=True, verbose_name="código")),
                (
                    "descricao",
                    models.CharField(max_length=300, verbose_name="descrição"),
                ),
                ("bu", models.CharField(blank=True, max_length=60, verbose_name="BU")),
                (
                    "segmento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="segmento"
                    ),
                ),
                (
                    "familia",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="família"
                    ),
                ),
                (
                    "ncm",
                    models.CharField(blank=True, max_length=20, verbose_name="NCM"),
                ),
                (
                    "ean",
                    models.CharField(blank=True, max_length=30, verbose_name="EAN"),
                ),
                (
                    "ipi",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=6,
                        verbose_name="IPI (%)",
                    ),
                ),
                (
                    "icms",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=6,
                        verbose_name="ICMS (%)",
                    ),
                ),
                (
                    "psd",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="PSD — Preço de Custo",
                    ),
                ),
                (
                    "pscf",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="PSCF — Preço de Venda",
                    ),
                ),
                (
                    "preco_referencia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("PSD", "PSD"),
                            ("PP", "PP"),
                            ("S/Controle de Venda", "S/Controle de Venda"),
                        ],
                        max_length=30,
                        verbose_name="controle de venda",
                    ),
                ),
                (
                    "qtd_multipla",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        max_digits=10,
                        verbose_name="qtd. múltipla",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
            ],
            options={
                "verbose_name": "produto",
                "verbose_name_plural": "produtos",
                "ordering": ["descricao"],
            },
        ),
    ]
