# Generated by Django 6.0.3 on 2026-03-25 14:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="quantidade_estoque",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=12,
                verbose_name="saldo em estoque",
            ),
        ),
    ]
