# Generated by Django 6.0.3 on 2026-08-13 21:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "desconto_maximo_balcao_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        help_text="Desconto efetivo máximo (soma de todos os descontos da venda, por item e no total) que um Vendedor pode aplicar sozinho no balcão. O grupo Administrador não é limitado por este valor.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="desconto máximo no balcão (%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "configuração",
                "verbose_name_plural": "configurações",
            },
        ),
    ]
