# Generated by Django 6.0.3 on 2026-08-13 22:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracao",
            name="inversor_sobrecarga_maxima_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("135.00"),
                help_text="Acima desse percentual, o inversor é marcado como incompatível por sobrecarga (clipping excessivo). 100% = potência do sistema igual à do inversor; a faixa padrão (80%–135%) segue a prática usual do mercado solar brasileiro.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("500")),
                ],
                verbose_name="relação CC:CA máxima aceita (%)",
            ),
        ),
        migrations.AddField(
            model_name="configuracao",
            name="inversor_sobrecarga_minima_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("80.00"),
                help_text="Abaixo desse percentual (potência do sistema ÷ potência do inversor), o inversor é marcado como incompatível na proposta solar por estar superdimensionado para o sistema.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("500")),
                ],
                verbose_name="relação CC:CA mínima aceita (%)",
            ),
        ),
    ]
