# Generated by Django 6.0.1 on 2026-08-16 10:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0002_configuracao_inversor_sobrecarga_maxima_pct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracao",
            name="cosip_mensal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("42.14"),
                help_text="Cobrança fixa da fatura que a geração solar nunca compensa. Entra na estimativa da conta que sobra depois do sistema.",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="contribuição de iluminação pública (R$/mês)",
            ),
        ),
        migrations.AddField(
            model_name="configuracao",
            name="tusd_fio_b_kwh",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("0.313783"),
                help_text="Parcela da tarifa que continua sendo cobrada sobre a energia compensada, conforme a Lei 14.300/2022. O padrão foi extraído de uma fatura real da Energisa TO (B1 residencial): a diferença entre a tarifa de consumo e a de energia injetada, dividida pelo percentual do Fio B vigente no ano da fatura.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="TUSD Fio B (R$/kWh, com tributos)",
            ),
        ),
    ]
