# Generated by Django 6.0.1 on 2026-08-16 12:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0003_configuracao_cosip_mensal_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuracao",
            name="tusd_fio_b_kwh",
        ),
        migrations.AddField(
            model_name="configuracao",
            name="icms_efetivo_injecao_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("7.30"),
                help_text="O crédito da energia injetada recebe ICMS menor que o consumo — no Tocantins a base de cálculo do ICMS da linha de injeção é só ~36% do valor (Lei estadual 1.287/2001, art. 27, VI). O padrão de 7,30% foi medido em duas faturas reais e reproduz a tarifa impressa com erro abaixo de 0,15%. Reconferir se a legislação estadual mudar.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="ICMS efetivo sobre energia injetada (%)",
            ),
        ),
        migrations.AddField(
            model_name="configuracao",
            name="icms_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("20.00"),
                help_text="Alíquota estadual cobrada “por dentro” no consumo. Tocantins: 20%.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="ICMS sobre energia (%)",
            ),
        ),
        migrations.AddField(
            model_name="configuracao",
            name="pis_cofins_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("9.25"),
                help_text="Soma de PIS (1,65%) e COFINS (7,60%), também cobrados “por dentro”.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="PIS + COFINS (%)",
            ),
        ),
    ]
