# Generated by Django 6.0.3 on 2026-03-20 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("servicos", "0001_initial"),
        ("solar", "0002_propostasolar"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "descricao",
                    models.CharField(max_length=300, verbose_name="descrição do item"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("solar", "Energia Solar"),
                            ("seguranca", "Segurança Eletrônica"),
                            ("automacao", "Automação"),
                            ("acesso", "Controle de Acesso"),
                            ("geral", "Geral"),
                        ],
                        max_length=20,
                        verbose_name="tipo de serviço",
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="ordem")),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
            ],
            options={
                "verbose_name": "item de checklist (template)",
                "verbose_name_plural": "itens de checklist (templates)",
                "ordering": ["tipo", "ordem", "descricao"],
            },
        ),
        migrations.CreateModel(
            name="Tecnico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="nome")),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "especialidade",
                    models.CharField(
                        choices=[
                            ("solar", "Energia Solar"),
                            ("seguranca", "Segurança Eletrônica"),
                            ("automacao", "Automação"),
                            ("acesso", "Controle de Acesso"),
                            ("geral", "Geral"),
                        ],
                        default="geral",
                        max_length=20,
                        verbose_name="especialidade",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
            ],
            options={
                "verbose_name": "técnico",
                "verbose_name_plural": "técnicos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="OrdemServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "numero",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="número",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("agendada", "Agendada"),
                            ("em_execucao", "Em Execução"),
                            ("concluida", "Concluída"),
                            ("faturada", "Faturada"),
                            ("reagendada", "Reagendada"),
                            ("suspensa", "Suspensa"),
                        ],
                        default="aberta",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("normal", "Normal"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="prioridade",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, verbose_name="descrição do serviço"),
                ),
                (
                    "data_agendamento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data do agendamento"
                    ),
                ),
                (
                    "data_inicio_execucao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="início da execução"
                    ),
                ),
                (
                    "data_conclusao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data de conclusão"
                    ),
                ),
                (
                    "assinatura_nome",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="nome de quem assinou"
                    ),
                ),
                (
                    "assinatura_confirmada",
                    models.BooleanField(
                        default=False, verbose_name="cliente confirmou a conclusão"
                    ),
                ),
                (
                    "assinatura_data",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data da assinatura"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordens_servico",
                        to="clientes.cliente",
                        verbose_name="cliente",
                    ),
                ),
                (
                    "proposta_servico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordens_servico",
                        to="servicos.propostaservico",
                        verbose_name="proposta de serviço",
                    ),
                ),
                (
                    "proposta_solar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordens_servico",
                        to="solar.propostasolar",
                        verbose_name="proposta solar",
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordens_servico",
                        to="ordens_servico.tecnico",
                        verbose_name="técnico responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "ordem de serviço",
                "verbose_name_plural": "ordens de serviço",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ItemChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=300, verbose_name="descrição"),
                ),
                (
                    "concluido",
                    models.BooleanField(default=False, verbose_name="concluído"),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="observação")),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="ordem")),
                (
                    "ordem_servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_checklist",
                        to="ordens_servico.ordemservico",
                        verbose_name="ordem de serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "item de checklist",
                "verbose_name_plural": "itens de checklist",
                "ordering": ["ordem", "pk"],
            },
        ),
        migrations.CreateModel(
            name="FotoOS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        upload_to="ordens_servico/fotos/%Y/%m/", verbose_name="foto"
                    ),
                ),
                (
                    "legenda",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="legenda"
                    ),
                ),
                (
                    "enviada_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="enviada em"),
                ),
                (
                    "ordem_servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="ordens_servico.ordemservico",
                        verbose_name="ordem de serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "foto da OS",
                "verbose_name_plural": "fotos da OS",
                "ordering": ["-enviada_em"],
            },
        ),
    ]
