# Generated by Django 6.0.3 on 2026-03-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordens_servico", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordemservico",
            name="status",
            field=models.CharField(
                choices=[
                    ("aberta", "Aberta"),
                    ("agendada", "Agendada"),
                    ("em_execucao", "Em Execução"),
                    ("concluida", "Concluída"),
                    ("faturada", "Faturada"),
                    ("suspensa", "Suspensa"),
                ],
                default="aberta",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
