# Generated by Django 6.0.3 on 2026-03-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("ordens_servico", "0002_alter_ordemservico_status"),
        ("servicos", "0002_alter_propostaservico_status"),
        ("solar", "0003_alter_propostasolar_status"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ordemservico",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("proposta_solar__isnull", False),
                    ("proposta_servico__isnull", False),
                    _negated=True,
                ),
                name="os_apenas_uma_proposta_origem",
            ),
        ),
    ]
