# Generated by Django 6.0.3 on 2026-03-23 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("balcao", "0001_initial"),
        ("clientes", "0001_initial"),
        ("ordens_servico", "0002_alter_ordemservico_status"),
        ("servicos", "0002_alter_propostaservico_status"),
        ("solar", "0003_alter_propostasolar_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LancamentoFinanceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "numero",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="número",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=300, verbose_name="descrição"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("parcial", "Parcial"),
                            ("liquidado", "Liquidado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                (
                    "valor_bruto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="valor bruto (R$)"
                    ),
                ),
                (
                    "desconto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="desconto (R$)",
                    ),
                ),
                (
                    "valor_liquido",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="valor líquido (R$)",
                    ),
                ),
                (
                    "valor_recebido",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="valor recebido (R$)",
                    ),
                ),
                (
                    "data_emissao",
                    models.DateField(auto_now_add=True, verbose_name="data de emissão"),
                ),
                (
                    "data_vencimento",
                    models.DateField(verbose_name="data de vencimento"),
                ),
                (
                    "data_liquidacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="data de liquidação"
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dinheiro", "Dinheiro"),
                            ("pix", "PIX"),
                            ("cartao_debito", "Cartão Débito"),
                            ("cartao_credito", "Cartão Crédito"),
                            ("boleto", "Boleto"),
                            ("crediario", "Crediário"),
                            ("transferencia", "Transferência Bancária"),
                        ],
                        max_length=20,
                        verbose_name="forma de pagamento",
                    ),
                ),
                (
                    "num_parcelas",
                    models.PositiveIntegerField(
                        default=1, verbose_name="nº de parcelas"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lancamentos",
                        to="clientes.cliente",
                        verbose_name="cliente",
                    ),
                ),
                (
                    "ordem_servico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lancamentos",
                        to="ordens_servico.ordemservico",
                        verbose_name="ordem de serviço",
                    ),
                ),
                (
                    "proposta_servico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lancamentos",
                        to="servicos.propostaservico",
                        verbose_name="proposta de serviço",
                    ),
                ),
                (
                    "proposta_solar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lancamentos",
                        to="solar.propostasolar",
                        verbose_name="proposta solar",
                    ),
                ),
                (
                    "venda_balcao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lancamentos",
                        to="balcao.venda",
                        verbose_name="venda balcão",
                    ),
                ),
            ],
            options={
                "verbose_name": "lançamento financeiro",
                "verbose_name_plural": "lançamentos financeiros",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ParcelaLancamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_parcela",
                    models.PositiveIntegerField(verbose_name="nº da parcela"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="valor (R$)"
                    ),
                ),
                ("data_vencimento", models.DateField(verbose_name="vencimento")),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="data de pagamento"
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="valor pago (R$)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("pago", "Pago"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                (
                    "observacao",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="observação"
                    ),
                ),
                (
                    "lancamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcelas",
                        to="financeiro.lancamentofinanceiro",
                        verbose_name="lançamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "parcela",
                "verbose_name_plural": "parcelas",
                "ordering": ["numero_parcela"],
                "unique_together": {("lancamento", "numero_parcela")},
            },
        ),
        migrations.CreateModel(
            name="BaixaFinanceira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="valor recebido (R$)",
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("dinheiro", "Dinheiro"),
                            ("pix", "PIX"),
                            ("cartao_debito", "Cartão Débito"),
                            ("cartao_credito", "Cartão Crédito"),
                            ("boleto", "Boleto"),
                            ("crediario", "Crediário"),
                            ("transferencia", "Transferência Bancária"),
                        ],
                        max_length=20,
                        verbose_name="forma de pagamento",
                    ),
                ),
                ("data_pagamento", models.DateField(verbose_name="data do pagamento")),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="registrado em"
                    ),
                ),
                (
                    "observacao",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="observação"
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registrado por",
                    ),
                ),
                (
                    "lancamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baixas",
                        to="financeiro.lancamentofinanceiro",
                        verbose_name="lançamento",
                    ),
                ),
                (
                    "parcela",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baixas",
                        to="financeiro.parcelalancamento",
                        verbose_name="parcela",
                    ),
                ),
            ],
            options={
                "verbose_name": "baixa financeira",
                "verbose_name_plural": "baixas financeiras",
                "ordering": ["-data_pagamento"],
            },
        ),
    ]
