# Generated by Django 6.0.3 on 2026-03-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balcao", "0001_initial"),
        ("clientes", "0001_initial"),
        ("financeiro", "0001_initial"),
        ("ordens_servico", "0002_alter_ordemservico_status"),
        ("servicos", "0002_alter_propostaservico_status"),
        ("solar", "0003_alter_propostasolar_status"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="lancamentofinanceiro",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("venda_balcao__isnull", False),
                        ("proposta_solar__isnull", False),
                        _negated=True,
                    ),
                    models.Q(
                        ("venda_balcao__isnull", False),
                        ("proposta_servico__isnull", False),
                        _negated=True,
                    ),
                    models.Q(
                        ("venda_balcao__isnull", False),
                        ("ordem_servico__isnull", False),
                        _negated=True,
                    ),
                    models.Q(
                        ("proposta_solar__isnull", False),
                        ("proposta_servico__isnull", False),
                        _negated=True,
                    ),
                    models.Q(
                        ("proposta_solar__isnull", False),
                        ("ordem_servico__isnull", False),
                        _negated=True,
                    ),
                    models.Q(
                        ("proposta_servico__isnull", False),
                        ("ordem_servico__isnull", False),
                        _negated=True,
                    ),
                ),
                name="financeiro_apenas_uma_origem",
            ),
        ),
    ]
