# Generated by Django 6.0.1 on 2026-08-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0002_lancamentofinanceiro_financeiro_apenas_uma_origem"),
    ]

    operations = [
        migrations.AddField(
            model_name="lancamentofinanceiro",
            name="tipo",
            field=models.CharField(
                choices=[("receita", "Receita"), ("repasse", "Repasse ao fornecedor")],
                default="receita",
                help_text="Receita: dinheiro que a Optimus realmente fatura e recebe. Repasse: o cliente paga direto ao fornecedor (ex.: equipamento solar, comprado sem margem da Optimus) — fica registrado para acompanhar se foi pago, mas não entra no faturamento da empresa.",
                max_length=10,
                verbose_name="tipo",
            ),
        ),
    ]
