# Generated by Django 6.0.3 on 2026-03-20 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("estoque", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="nome")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("seguranca", "Segurança Eletrônica"),
                            ("automacao", "Automação"),
                            ("acesso", "Controle de Acesso"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="descrição")),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
            ],
            options={
                "verbose_name": "Serviço",
                "verbose_name_plural": "Serviços",
                "ordering": ["tipo", "nome"],
            },
        ),
        migrations.CreateModel(
            name="PropostaServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "numero",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="número",
                    ),
                ),
                (
                    "tipo_servico",
                    models.CharField(
                        choices=[
                            ("seguranca", "Segurança Eletrônica"),
                            ("automacao", "Automação"),
                            ("acesso", "Controle de Acesso"),
                        ],
                        max_length=20,
                        verbose_name="tipo de serviço",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("enviada", "Enviada"),
                            ("aprovada", "Aprovada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="rascunho",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("validade", models.DateField(verbose_name="validade da proposta")),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="propostas_servico",
                        to="clientes.cliente",
                        verbose_name="cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposta de Serviço",
                "verbose_name_plural": "Propostas de Serviço",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ItemProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(default=1, verbose_name="quantidade"),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="valor unitário (R$)",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="estoque.produto",
                        verbose_name="produto",
                    ),
                ),
                (
                    "proposta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_produto",
                        to="servicos.propostaservico",
                        verbose_name="proposta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Produto",
                "verbose_name_plural": "Itens de Produto",
            },
        ),
        migrations.CreateModel(
            name="ItemServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="valor (R$)"
                    ),
                ),
                (
                    "observacao",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="observação"
                    ),
                ),
                (
                    "proposta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_servico",
                        to="servicos.propostaservico",
                        verbose_name="proposta",
                    ),
                ),
                (
                    "servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="servicos.servico",
                        verbose_name="serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Serviço",
                "verbose_name_plural": "Itens de Serviço",
            },
        ),
    ]
