# Generated by Django 6.0.3 on 2026-03-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propostaservico",
            name="status",
            field=models.CharField(
                choices=[
                    ("rascunho", "Rascunho"),
                    ("enviada", "Enviada"),
                    ("aprovada", "Aprovada"),
                    ("concluida", "Concluída"),
                    ("cancelada", "Cancelada"),
                ],
                default="rascunho",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
