# Generated by Django 6.0.3 on 2026-03-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EstruturaFixacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "fabricante",
                    models.CharField(max_length=100, verbose_name="fabricante"),
                ),
                ("modelo", models.CharField(max_length=100, verbose_name="modelo")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ceramico", "Telha Cerâmica"),
                            ("metalico", "Telha Metálica"),
                            ("fibrocimento", "Telha Fibrocimento"),
                            ("laje", "Laje"),
                            ("solo", "Solo"),
                        ],
                        max_length=20,
                        verbose_name="tipo de instalação",
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("aluminio", "Alumínio"),
                            ("aco_galvanizado", "Aço Galvanizado"),
                        ],
                        default="aluminio",
                        max_length=20,
                        verbose_name="material",
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="descrição")),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
            ],
            options={
                "verbose_name": "estrutura de fixação",
                "verbose_name_plural": "estruturas de fixação",
                "ordering": ["fabricante", "tipo"],
            },
        ),
        migrations.CreateModel(
            name="Inversor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "fabricante",
                    models.CharField(max_length=100, verbose_name="fabricante"),
                ),
                ("modelo", models.CharField(max_length=100, verbose_name="modelo")),
                (
                    "potencia_kw",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="potência (kW)"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("micro", "Microinversor"),
                            ("hibrido", "Híbrido"),
                        ],
                        default="string",
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "fase",
                    models.CharField(
                        choices=[
                            ("monofasico", "Monofásico"),
                            ("trifasico", "Trifásico"),
                        ],
                        default="monofasico",
                        max_length=10,
                        verbose_name="fase",
                    ),
                ),
                (
                    "tensao_max_entrada",
                    models.IntegerField(verbose_name="tensão máx. entrada (V)"),
                ),
                (
                    "quantidade_mppt",
                    models.IntegerField(verbose_name="quantidade de MPPTs"),
                ),
                ("garantia", models.IntegerField(verbose_name="garantia (anos)")),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
            ],
            options={
                "verbose_name": "inversor",
                "verbose_name_plural": "inversores",
                "ordering": ["fabricante", "potencia_kw"],
            },
        ),
        migrations.CreateModel(
            name="ModuloFotovoltaico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "fabricante",
                    models.CharField(max_length=100, verbose_name="fabricante"),
                ),
                ("modelo", models.CharField(max_length=100, verbose_name="modelo")),
                ("potencia_wp", models.IntegerField(verbose_name="potência (Wp)")),
                (
                    "eficiencia",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="eficiência (%)"
                    ),
                ),
                (
                    "voc",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="tensão circuito aberto - Voc (V)",
                    ),
                ),
                (
                    "isc",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="corrente curto-circuito - Isc (A)",
                    ),
                ),
                ("largura", models.IntegerField(verbose_name="largura (mm)")),
                ("altura", models.IntegerField(verbose_name="altura (mm)")),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="peso (kg)"
                    ),
                ),
                (
                    "garantia_produto",
                    models.IntegerField(verbose_name="garantia do produto (anos)"),
                ),
                (
                    "garantia_desempenho",
                    models.IntegerField(verbose_name="garantia de desempenho (anos)"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
            ],
            options={
                "verbose_name": "módulo fotovoltaico",
                "verbose_name_plural": "módulos fotovoltaicos",
                "ordering": ["fabricante", "modelo"],
            },
        ),
    ]
