# Generated by Django 6.0.3 on 2026-03-19 05:58

import django.db.models.deletion
import solar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("solar", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropostaSolar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "numero",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="número",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("enviada", "Enviada"),
                            ("aprovada", "Aprovada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="rascunho",
                        max_length=12,
                        verbose_name="status",
                    ),
                ),
                (
                    "consumo_medio_kwh",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="consumo médio mensal (kWh)",
                    ),
                ),
                (
                    "hsp",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.5,
                        max_digits=4,
                        verbose_name="HSP — horas de sol pleno (h/dia)",
                    ),
                ),
                (
                    "fator_eficiencia",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.75,
                        max_digits=4,
                        verbose_name="fator de eficiência do sistema",
                    ),
                ),
                (
                    "potencia_kwp",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=7,
                        verbose_name="potência do sistema (kWp)",
                    ),
                ),
                (
                    "quantidade_modulos",
                    models.IntegerField(verbose_name="quantidade de módulos"),
                ),
                (
                    "valor_equipamentos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="valor dos equipamentos (R$)",
                    ),
                ),
                (
                    "valor_instalacao",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="valor da instalação (R$)",
                    ),
                ),
                (
                    "validade",
                    models.DateField(
                        default=solar.models._validade_padrao,
                        verbose_name="validade da proposta",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clientes.cliente",
                        verbose_name="cliente",
                    ),
                ),
                (
                    "estrutura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="solar.estruturafixacao",
                        verbose_name="estrutura de fixação",
                    ),
                ),
                (
                    "inversor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="solar.inversor",
                        verbose_name="inversor",
                    ),
                ),
                (
                    "modulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="solar.modulofotovoltaico",
                        verbose_name="módulo fotovoltaico",
                    ),
                ),
            ],
            options={
                "verbose_name": "proposta solar",
                "verbose_name_plural": "propostas solares",
                "ordering": ["-criado_em"],
            },
        ),
    ]
