# Generated by Django 6.0.3 on 2026-04-13 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar", "0003_alter_propostasolar_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propostasolar",
            name="valor_equipamentos",
        ),
        migrations.CreateModel(
            name="ItemPropostaSolar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.IntegerField(default=1, verbose_name="quantidade"),
                ),
                (
                    "preco_venda_snapshot",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="preço de venda (snapshot)",
                    ),
                ),
                (
                    "preco_custo_snapshot",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="preço de custo (snapshot)",
                    ),
                ),
                (
                    "data_referencia_preco",
                    models.DateField(verbose_name="data de referência do preço"),
                ),
                (
                    "estrutura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="solar.estruturafixacao",
                        verbose_name="estrutura",
                    ),
                ),
                (
                    "inversor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="solar.inversor",
                        verbose_name="inversor",
                    ),
                ),
                (
                    "modulo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="solar.modulofotovoltaico",
                        verbose_name="módulo",
                    ),
                ),
                (
                    "proposta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="solar.propostasolar",
                        verbose_name="proposta",
                    ),
                ),
            ],
            options={
                "verbose_name": "item da proposta solar",
                "verbose_name_plural": "itens da proposta solar",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("estrutura__isnull", True),
                                ("inversor__isnull", True),
                                ("modulo__isnull", False),
                            ),
                            models.Q(
                                ("estrutura__isnull", True),
                                ("inversor__isnull", False),
                                ("modulo__isnull", True),
                            ),
                            models.Q(
                                ("estrutura__isnull", False),
                                ("inversor__isnull", True),
                                ("modulo__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="item_proposta_solar_apenas_um_tipo",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PrecoEquipamentoSolar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "preco_custo",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="preço de custo (R$)",
                    ),
                ),
                (
                    "preco_venda",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="preço de venda (R$)",
                    ),
                ),
                ("vigente_desde", models.DateField(verbose_name="vigente desde")),
                (
                    "vigente_ate",
                    models.DateField(blank=True, null=True, verbose_name="vigente até"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criado por",
                    ),
                ),
                (
                    "estrutura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="solar.estruturafixacao",
                        verbose_name="estrutura",
                    ),
                ),
                (
                    "inversor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="solar.inversor",
                        verbose_name="inversor",
                    ),
                ),
                (
                    "modulo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="solar.modulofotovoltaico",
                        verbose_name="módulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "preço de equipamento solar",
                "verbose_name_plural": "preços de equipamentos solares",
                "ordering": ["-vigente_desde"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("estrutura__isnull", True),
                                ("inversor__isnull", True),
                                ("modulo__isnull", False),
                            ),
                            models.Q(
                                ("estrutura__isnull", True),
                                ("inversor__isnull", False),
                                ("modulo__isnull", True),
                            ),
                            models.Q(
                                ("estrutura__isnull", False),
                                ("inversor__isnull", True),
                                ("modulo__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="preco_solar_apenas_um_tipo",
                    )
                ],
            },
        ),
    ]
