# Generated by Django 6.0.3 on 2026-04-13 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar", "0005_popular_precos_iniciais"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MateriaisEletricos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "fabricante",
                    models.CharField(max_length=100, verbose_name="fabricante"),
                ),
                (
                    "modelo",
                    models.CharField(
                        max_length=100, verbose_name="modelo / referência"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("cabo", "Cabo"),
                            ("disjuntor", "Disjuntor"),
                            ("eletroduto", "Eletroduto"),
                            ("dps", "DPS / Protetor de Surto"),
                            ("outros", "Outros"),
                        ],
                        default="outros",
                        max_length=20,
                        verbose_name="categoria",
                    ),
                ),
                (
                    "unidade",
                    models.CharField(
                        choices=[("m", "Metro (m)"), ("pc", "Peça (pc)")],
                        default="pc",
                        max_length=5,
                        verbose_name="unidade de medida",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, verbose_name="descrição / especificação"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
            ],
            options={
                "verbose_name": "material elétrico",
                "verbose_name_plural": "materiais elétricos",
                "ordering": ["categoria", "fabricante", "modelo"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="itempropostasolar",
            name="item_proposta_solar_apenas_um_tipo",
        ),
        migrations.RemoveConstraint(
            model_name="precoequipamentosolar",
            name="preco_solar_apenas_um_tipo",
        ),
        migrations.AddField(
            model_name="itempropostasolar",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="solar.materiaiseletricos",
                verbose_name="material elétrico",
            ),
        ),
        migrations.AddField(
            model_name="precoequipamentosolar",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="solar.materiaiseletricos",
                verbose_name="material elétrico",
            ),
        ),
        migrations.AddConstraint(
            model_name="itempropostasolar",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("estrutura__isnull", True),
                        ("inversor__isnull", True),
                        ("material__isnull", True),
                        ("modulo__isnull", False),
                    ),
                    models.Q(
                        ("estrutura__isnull", True),
                        ("inversor__isnull", False),
                        ("material__isnull", True),
                        ("modulo__isnull", True),
                    ),
                    models.Q(
                        ("estrutura__isnull", False),
                        ("inversor__isnull", True),
                        ("material__isnull", True),
                        ("modulo__isnull", True),
                    ),
                    models.Q(
                        ("estrutura__isnull", True),
                        ("inversor__isnull", True),
                        ("material__isnull", False),
                        ("modulo__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="item_proposta_solar_apenas_um_tipo",
            ),
        ),
        migrations.AddConstraint(
            model_name="precoequipamentosolar",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("estrutura__isnull", True),
                        ("inversor__isnull", True),
                        ("material__isnull", True),
                        ("modulo__isnull", False),
                    ),
                    models.Q(
                        ("estrutura__isnull", True),
                        ("inversor__isnull", False),
                        ("material__isnull", True),
                        ("modulo__isnull", True),
                    ),
                    models.Q(
                        ("estrutura__isnull", False),
                        ("inversor__isnull", True),
                        ("material__isnull", True),
                        ("modulo__isnull", True),
                    ),
                    models.Q(
                        ("estrutura__isnull", True),
                        ("inversor__isnull", True),
                        ("material__isnull", False),
                        ("modulo__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="preco_solar_apenas_um_tipo",
            ),
        ),
    ]
