# Generated by Django 6.0.3 on 2026-04-13 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar", "0006_materiaiseletricos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="precoequipamentosolar",
            name="estrutura",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="solar.estruturafixacao",
                verbose_name="estrutura",
            ),
        ),
        migrations.AlterField(
            model_name="precoequipamentosolar",
            name="inversor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="solar.inversor",
                verbose_name="inversor",
            ),
        ),
        migrations.AlterField(
            model_name="precoequipamentosolar",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="solar.materiaiseletricos",
                verbose_name="material elétrico",
            ),
        ),
        migrations.AlterField(
            model_name="precoequipamentosolar",
            name="modulo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="solar.modulofotovoltaico",
                verbose_name="módulo",
            ),
        ),
    ]
