# Generated by Django 6.0.1 on 2026-04-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar", "0007_preco_equipamento_cascade"),
    ]

    operations = [
        migrations.AddField(
            model_name="propostasolar",
            name="quantidade_estruturas",
            field=models.IntegerField(
                default=1, verbose_name="quantidade de estruturas"
            ),
        ),
        migrations.AddField(
            model_name="propostasolar",
            name="quantidade_inversores",
            field=models.IntegerField(
                default=1, verbose_name="quantidade de inversores"
            ),
        ),
    ]
