# Generated by Django 6.0.1 on 2026-04-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("solar", "0008_propostasolar_quantidade_estruturas_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propostasolar",
            name="estrutura",
        ),
        migrations.RemoveField(
            model_name="propostasolar",
            name="inversor",
        ),
        migrations.RemoveField(
            model_name="propostasolar",
            name="quantidade_estruturas",
        ),
        migrations.RemoveField(
            model_name="propostasolar",
            name="quantidade_inversores",
        ),
    ]
