# Generated by Django 6.0.3 on 2026-04-14 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar", "0009_remove_propostasolar_estrutura_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propostasolar",
            name="modulo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="solar.modulofotovoltaico",
                verbose_name="módulo fotovoltaico",
            ),
        ),
        migrations.AlterField(
            model_name="propostasolar",
            name="quantidade_modulos",
            field=models.IntegerField(default=0, verbose_name="quantidade de módulos"),
        ),
    ]
