# Generated by Django 6.0.3 on 2026-08-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar", "0010_modulo_nullable_quantidade_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxaCartao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "forma",
                    models.CharField(
                        choices=[
                            ("debito", "Débito"),
                            ("credito", "Crédito"),
                            ("pix", "PIX"),
                        ],
                        max_length=10,
                        verbose_name="forma",
                    ),
                ),
                (
                    "bandeira",
                    models.CharField(
                        choices=[
                            ("visa_master", "Visa ou Master"),
                            ("amex", "Amex"),
                            ("elo", "Elo"),
                            ("hiper", "Hiper"),
                        ],
                        max_length=15,
                        verbose_name="bandeira",
                    ),
                ),
                (
                    "parcelas",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="1 para débito/PIX/crédito à vista; 2 a 21 para crédito parcelado.",
                        verbose_name="parcelas",
                    ),
                ),
                (
                    "percentual",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="acréscimo (%)"
                    ),
                ),
            ],
            options={
                "verbose_name": "taxa de cartão",
                "verbose_name_plural": "taxas de cartão",
                "ordering": ["bandeira", "forma", "parcelas"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("forma", "bandeira", "parcelas"),
                        name="taxa_cartao_unica_por_combinacao",
                    )
                ],
            },
        ),
    ]
