# Generated by Django 6.0.1 on 2026-08-16 10:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar", "0011_taxacartao"),
    ]

    operations = [
        migrations.AddField(
            model_name="propostasolar",
            name="autoconsumo_simultaneo_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("25.00"),
                help_text="Quanto da geração o cliente consome no mesmo instante em que é produzida (não passa pela rede, logo não sofre Fio B e economiza a tarifa cheia). Residencial costuma ficar em 20–30%; comércio com carga diurna chega a 50–70%.",
                max_digits=5,
                verbose_name="autoconsumo simultâneo (%)",
            ),
        ),
        migrations.AddField(
            model_name="propostasolar",
            name="tarifa_kwh",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Com tributos, como aparece na fatura na linha “Consumo em kWh”. Opcional — sem ela o PDF não mostra a análise de retorno.",
                max_digits=10,
                null=True,
                verbose_name="tarifa de energia do cliente (R$/kWh)",
            ),
        ),
        migrations.AddField(
            model_name="propostasolar",
            name="tipo_ligacao",
            field=models.CharField(
                choices=[
                    ("monofasico", "Monofásico (mínimo 30 kWh)"),
                    ("bifasico", "Bifásico (mínimo 50 kWh)"),
                    ("trifasico", "Trifásico (mínimo 100 kWh)"),
                ],
                default="monofasico",
                help_text="Define o custo de disponibilidade — o mínimo que o cliente paga mesmo gerando toda a energia.",
                max_length=12,
                verbose_name="tipo de ligação",
            ),
        ),
    ]
