# Generated by Django 6.0.1 on 2026-08-16 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar", "0012_propostasolar_autoconsumo_simultaneo_pct_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Distribuidora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                ("nome", models.CharField(max_length=120, verbose_name="nome")),
                (
                    "sigla",
                    models.CharField(
                        help_text="Como aparece no campo SigNomeAgente da ANEEL. Ex.: ETO.",
                        max_length=20,
                        verbose_name="sigla ANEEL",
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        max_length=14, unique=True, verbose_name="CNPJ (só dígitos)"
                    ),
                ),
                ("uf", models.CharField(max_length=2, verbose_name="UF")),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
            ],
            options={
                "verbose_name": "distribuidora",
                "verbose_name_plural": "distribuidoras",
                "ordering": ["uf", "nome"],
            },
        ),
        migrations.AddField(
            model_name="propostasolar",
            name="distribuidora",
            field=models.ForeignKey(
                blank=True,
                help_text="Define a tarifa homologada e o Fio B usados na análise de retorno, direto da ANEEL.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="solar.distribuidora",
                verbose_name="distribuidora do cliente",
            ),
        ),
        migrations.CreateModel(
            name="TarifaDistribuidora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "subgrupo",
                    models.CharField(
                        default="B1", max_length=10, verbose_name="subgrupo tarifário"
                    ),
                ),
                (
                    "modalidade",
                    models.CharField(
                        default="Convencional", max_length=40, verbose_name="modalidade"
                    ),
                ),
                (
                    "subclasse",
                    models.CharField(
                        default="Residencial", max_length=80, verbose_name="subclasse"
                    ),
                ),
                (
                    "vigencia_inicio",
                    models.DateField(verbose_name="início da vigência"),
                ),
                (
                    "vigencia_fim",
                    models.DateField(
                        blank=True, null=True, verbose_name="fim da vigência"
                    ),
                ),
                (
                    "vlr_tusd",
                    models.DecimalField(
                        decimal_places=6, max_digits=12, verbose_name="TUSD (R$/MWh)"
                    ),
                ),
                (
                    "vlr_te",
                    models.DecimalField(
                        decimal_places=6, max_digits=12, verbose_name="TE (R$/MWh)"
                    ),
                ),
                (
                    "vlr_tusd_fio_b",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=12,
                        verbose_name="TUSD Fio B (R$/MWh)",
                    ),
                ),
                (
                    "sincronizado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="sincronizado em"
                    ),
                ),
                (
                    "distribuidora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifas",
                        to="solar.distribuidora",
                        verbose_name="distribuidora",
                    ),
                ),
            ],
            options={
                "verbose_name": "tarifa da distribuidora",
                "verbose_name_plural": "tarifas das distribuidoras",
                "ordering": ["distribuidora", "-vigencia_inicio", "subclasse"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "distribuidora",
                            "subgrupo",
                            "modalidade",
                            "subclasse",
                            "vigencia_inicio",
                        ),
                        name="tarifa_aneel_unica_por_vigencia",
                    )
                ],
            },
        ),
    ]
