# Generated by Django 6.0.1 on 2026-08-16 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar", "0013_distribuidora_propostasolar_distribuidora_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "codigo_ibge",
                    models.IntegerField(unique=True, verbose_name="código IBGE"),
                ),
                ("nome", models.CharField(max_length=120, verbose_name="nome")),
                ("uf", models.CharField(max_length=2, verbose_name="UF")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="longitude",
                    ),
                ),
                (
                    "hsp_mensal",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Climatologia NASA POWER, no formato {"1": 5.39, ..., "12": 5.46}.',
                        verbose_name="HSP por mês (kWh/m²/dia)",
                    ),
                ),
                (
                    "hsp_anual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="HSP médio anual (h/dia)",
                    ),
                ),
                (
                    "sincronizado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="HSP sincronizado em"
                    ),
                ),
            ],
            options={
                "verbose_name": "município",
                "verbose_name_plural": "municípios",
                "ordering": ["uf", "nome"],
            },
        ),
        migrations.AddField(
            model_name="propostasolar",
            name="municipio",
            field=models.ForeignKey(
                blank=True,
                help_text="Onde o gerador vai ser instalado — nem sempre é onde o cliente mora. Define o HSP e a curva de geração mês a mês.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="solar.municipio",
                verbose_name="município da instalação",
            ),
        ),
    ]
