# Generated by Django 6.0.1 on 2026-08-16 22:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar", "0014_municipio_propostasolar_municipio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inversor",
            name="potencia_kw",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Em kW, não em W. Um inversor “6K” são 6 kW.",
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.1")),
                    django.core.validators.MaxValueValidator(Decimal("500")),
                ],
                verbose_name="potência (kW)",
            ),
        ),
        migrations.AlterField(
            model_name="modulofotovoltaico",
            name="potencia_wp",
            field=models.IntegerField(
                help_text="Em Wp, não em kWp. Um módulo de 610 W se cadastra como 610.",
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(2000),
                ],
                verbose_name="potência (Wp)",
            ),
        ),
    ]
