# Generated by Django 6.0.1 on 2026-08-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar", "0015_alter_inversor_potencia_kw_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propostasolar",
            name="valor_equipamentos_manual",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Sobrepõe a soma calculada dos itens. Útil quando o vendedor já sabe o valor total cotado pelo fornecedor (Intelbras, Belenus) sem precisar que cada item do catálogo tenha preço vigente cadastrado — o cliente paga esse valor direto ao fornecedor, sem margem da Optimus (ver skill financeiro-domain).",
                max_digits=12,
                null=True,
                verbose_name="custo de equipamentos (R$, editável)",
            ),
        ),
    ]
