# Generated by Django 6.0.3 on 2026-03-23 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("balcao", "0001_initial"),
        ("clientes", "0001_initial"),
        ("ordens_servico", "0002_alter_ordemservico_status"),
        ("servicos", "0002_alter_propostaservico_status"),
        ("solar", "0003_alter_propostasolar_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chamado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "numero",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="número",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("suporte", "Suporte Técnico"),
                            ("garantia", "Garantia"),
                            ("reclamacao", "Reclamação"),
                            ("manutencao", "Manutenção"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberto", "Aberto"),
                            ("em_atendimento", "Em Atendimento"),
                            ("aguardando_cliente", "Aguardando Cliente"),
                            ("resolvido", "Resolvido"),
                            ("encerrado", "Encerrado"),
                        ],
                        default="aberto",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("normal", "Normal"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="prioridade",
                    ),
                ),
                ("assunto", models.CharField(max_length=300, verbose_name="assunto")),
                ("descricao", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "prazo",
                    models.DateField(
                        blank=True, null=True, verbose_name="prazo de resolução"
                    ),
                ),
                (
                    "data_resolucao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data de resolução"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chamados",
                        to="clientes.cliente",
                        verbose_name="cliente",
                    ),
                ),
                (
                    "ordem_servico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chamados",
                        to="ordens_servico.ordemservico",
                        verbose_name="OS de origem",
                    ),
                ),
                (
                    "proposta_servico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chamados",
                        to="servicos.propostaservico",
                        verbose_name="proposta de serviço de origem",
                    ),
                ),
                (
                    "proposta_solar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chamados",
                        to="solar.propostasolar",
                        verbose_name="proposta solar de origem",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chamados_responsavel",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="responsável",
                    ),
                ),
                (
                    "venda_balcao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chamados",
                        to="balcao.venda",
                        verbose_name="venda de origem",
                    ),
                ),
            ],
            options={
                "verbose_name": "chamado",
                "verbose_name_plural": "chamados",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="InteracaoChamado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("comentario", "Comentário interno"),
                            ("ligacao", "Ligação"),
                            ("email", "E-mail"),
                            ("visita", "Visita técnica"),
                            ("resolucao", "Resolução"),
                        ],
                        default="comentario",
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                ("texto", models.TextField(verbose_name="descrição")),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="registrado em"
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="autor",
                    ),
                ),
                (
                    "chamado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interacoes",
                        to="pos_venda.chamado",
                        verbose_name="chamado",
                    ),
                ),
            ],
            options={
                "verbose_name": "interação",
                "verbose_name_plural": "interações",
                "ordering": ["criado_em"],
            },
        ),
    ]
