# Generated by Django 6.0.3 on 2026-03-23 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balcao", "0001_initial"),
        ("clientes", "0001_initial"),
        ("ordens_servico", "0003_ordemservico_os_apenas_uma_proposta_origem"),
        ("pos_venda", "0001_initial"),
        ("servicos", "0002_alter_propostaservico_status"),
        ("solar", "0003_alter_propostasolar_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="chamado",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("ordem_servico__isnull", False),
                        ("proposta_solar__isnull", False),
                        _negated=True,
                    ),
                    models.Q(
                        ("ordem_servico__isnull", False),
                        ("proposta_servico__isnull", False),
                        _negated=True,
                    ),
                    models.Q(
                        ("ordem_servico__isnull", False),
                        ("venda_balcao__isnull", False),
                        _negated=True,
                    ),
                    models.Q(
                        ("proposta_solar__isnull", False),
                        ("proposta_servico__isnull", False),
                        _negated=True,
                    ),
                    models.Q(
                        ("proposta_solar__isnull", False),
                        ("venda_balcao__isnull", False),
                        _negated=True,
                    ),
                    models.Q(
                        ("proposta_servico__isnull", False),
                        ("venda_balcao__isnull", False),
                        _negated=True,
                    ),
                ),
                name="pos_venda_apenas_uma_origem",
            ),
        ),
    ]
